version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rpg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpg_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rpg_app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rpg_db
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    restart: always

volumes:
  pg_data: